vars:
  stage: rawtest

components:
  terraform:
    first:
      metadata:
        component: first

    second:
      metadata:
        component: second
      vars:
        input_from_first: '{{ (atmos.Component "first" .stack).outputs.first_output | toRawJson }}'
        test_string: '{{ (atmos.Component "first" .stack).outputs.first_output.test_string }}'
        test_number: '{{ (atmos.Component "first" .stack).outputs.first_output.test_number }}'
        test_bool: '{{ (atmos.Component "first" .stack).outputs.first_output.test_bool }}'
        test_list: '{{ (atmos.Component "first" .stack).outputs.first_output.test_list | toRawJson }}'
        test_map: '{{ (atmos.Component "first" .stack).outputs.first_output.test_map | toRawJson }}'
        test_tuple: '{{ (atmos.Component "first" .stack).outputs.first_output.test_tuple | toRawJson }}'
        test_object: '{{ (atmos.Component "first" .stack).outputs.first_output.test_object | toRawJson }}'
        test_null: '{{ (atmos.Component "first" .stack).outputs.first_output.test_null | toRawJson }}'
        test_null_string: '{{ (atmos.Component "first" .stack).outputs.first_output.test_null_string | toRawJson }}'

        # (Incorrect Example) Passing null values in as a templated value without using toJson or toRawJson
        # results in a string object with a value of "<no value>"
        test_not_actually_null_string: '{{ (atmos.Component "first" .stack).outputs.first_output.test_null_string }}'

        test_json_string: '{{ (atmos.Component "first" .stack).outputs.first_output.test_json_string | toRawJson }}'
        test_object_from_json_string: '{{ (atmos.Component "first" .stack).outputs.first_output.test_json_string }}'
